### ISSUE TITLE
CCM configures all external networks with IP auto-assignment for metalLB

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-ccm#18]
Not fully sure if this a real issue at the moment, but we saw that during Kubernetes cluster creation the kube-apiserver was getting an IP address of an external network that has no internet connectivity. This prevented the cluster from coming up.

I would assume that only the default external network should have enabled IP auto-assigment for MetalLB?

**Comment by Gerrit91** [comment]
@mwennrich @mwindower Any opinion about this?

**Comment by mwennrich** [comment]
True, auto-assign should only be set for the DefaultExternalNetwork
